# -*- coding: utf-8 -*-
from . import employee
from . import event_track
from . import event_type
from . import survey
from . import mapped_items
from . import event_schedule
from . import event
from . import event_period
from . import term
from . import company_price
from . import event_price
from . import course_topic
from . import event_mail
from . import course
from . import course_mail
#from . import document
#from . import attachment
from . import program
from . import instructor_rate
from . import purchase_order
from . import event_registration
from . import session_registration
from . import sale_order_line
from . import resume_line
from . import resume_line_type
from . import hr_employee_skill
from . import education_account
from . import res_partner
from . import certificate
from . import employee
from . import account_journal
from . import stock_warehouse
from . import res_company
from . import attempt
from . import industry
from . import product
from . import event_location
from . import exam
from . import company_price
from . import company_topic_price
from . import course_ticket
from . import hr_contract
from . import account_tax
#from . import marketing_campaign
from . import education_level
from . import universities
from . import majors
#from . import crm_lead
from . import hr_attendance
from . import instructor_major
from . import university
from . import event_ticket
from . import res_currency
from . import product_pricelist
from . import ir_sequence
from . import pricelist_item
from . import factor_of_decision
from . import worked_days
from . import hr_payslip
from . import shipping_price
from . import delivery_carrier
from . import account_payment
from . import attendance
from . import sale_forecast
from . import hr_expense
from . import sale_coupon_program
from . import slide_slide
from . import stock_move_line
from . import stock_quant
#from . import calendar_event
from . import product_registration