# -*- coding: utf-8 -*-
{
    'name': "Training.",
    'summary': """
        Manage Your Entire Training Operation""",
    'description': """
    """,
    'author': "Business Solution Advisors",
    'website': "http://www.bsa-me.com",
    'category': 'Website',
    'version': '0.11',
    'depends': [
        'base',
        'hr',
        'hr_payroll',
        'hr_attendance',
        'hr_expense',
        'hr_holidays',
        'note',
        'website_sale',
        'board',
        'website_event',
        'website_event_questions',
        'website_event_track',
        'survey',
        'purchase',
        'sale_management',
        'account_accountant',
        'account',
        'hr_expense',
        'hr_skills',
        'hr_skills_slides',
        'hr_skills_survey',
        'stock',
        'stock_barcode',
        'contacts',
        'timesheet_grid',
        'survey',
        'website_slides',
        'website_forum',
        'delivery',
        'website_sale_delivery',
        'sale_coupon',
    ],
    'data': [
        'security/groups.xml',
        #'security/record_rules.xml',
        'security/ir.model.access.csv',
        'views/data.xml',
        'views/views.xml',
        'views/templates.xml',
        'views/employee.xml',
        'views/event.xml',
        'views/survey.xml',
        'views/operationhub.xml',
        'views/course.xml',
        'views/menu_items.xml',
        'views/company.xml',
        'views/sessions.xml',
        'views/res_partner.xml',
        'views/assets.xml',
        'views/resume_line_type.xml',
        'views/resume_line.xml',
        #'views/sale_order.xml',
        'views/ir_sequence.xml',
        #'wizard/event_track_create_timesheet.xml',
        'data/salary_structure.xml',
        'data/server_actions.xml',
        'data/session_sale_data.xml',
        'data/templates.xml',
        #'data/update_menu.xml',
        #'wizard/session_edit_registration.xml',
        #'wizard/event_configurator_views.xml',
        'wizard/purchase_comment_wizard.xml',
        'views/purchase.xml',
        'views/payslip.xml',
        'data/paper_formats.xml',
        'views/reports.xml',
        'views/carrier.xml',
        #'views/account_journal.xml',
        'views/sale_coupon_program.xml',
        'views/slide_slide.xml',
        'views/pricelist_item.xml',
        'views/survey_question.xml',
        'views/stock_quant.xml',
        'views/stock_move_line.xml',
        'views/product_registration.xml',
        #'views/account_payment.xml'
    ],
    'application': True,
    'demo': [
        'demo/demo.xml',
    ],
}
